version: "3.3"
services:
    web:
        build: .
        ports:
          - "5009:5009"
        volumes:
          - type: bind
            source:
            target: /root/.qualipy
        depends_on:
          - redis
        environment:
          - CACHE_REDIS_URL=redis://redis:6379
          - QUALIPY_CONFIG_DIR=/root/.qualipy
          - QUALIPY_HOST=0.0.0.0
          - QUALIPY_PORT=5009
          - QUALIPY_ENGINE=gunicorn
          - QUALIPY_TRAIN_ANOMALY=True
    redis:
        image: redis
