"""Add new fields to project table

Revision ID: d98f2fbc6aaa
Revises: 
Create Date: 2022-11-19 10:56:02.890452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98f2fbc6aaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('config_repr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'config_repr')
    op.drop_column('project', 'date_created')
    # ### end Alembic commands ###
